function plot_each_collision(gsr,collision_times,collision_source,gsr_responses,...
        title_str,has_cvx,baseline_before,scr_window,scl_end,t_trial_start,t_trial_end)
    n=numel(collision_times); n_cols=min(3,n); n_rows=ceil(n/n_cols);
    figure('Name',['Collision Detail: ' title_str],'Position',[50 50 n_cols*500 n_rows*360]);
    for i = 1:n
        ax = subplot(n_rows,n_cols,i);
        plot_collision_panel(ax,gsr,get_gsr_col(gsr),get_gsr_label(gsr),...
            collision_times(i),collision_source(i),gsr_responses(i),i,n,...
            has_cvx,baseline_before,scr_window,scl_end,t_trial_start,t_trial_end);
    end
    sgtitle(['Collisions: ' title_str ' | A=accel  F=force  B=both | red=SCR+SCL  mag=SCR  cyan=SCL'],...
        'FontWeight','bold','FontSize',8);
end